# <span style="color:red; font-family:Georgia; font-size:2em;">AAN - Mini Projet 1 </span>

In [1]:
from sklearn import datasets
import math
iris = datasets.load_iris()
print (iris.data)
print (iris.target)


[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

# <span style="color:green; font-family:Georgia; font-size:1.5em;">1. Division de l’echantillon d’apprentissage </span>

In [7]:
import numpy as np
import matplotlib.pyplot as plt

Ciris = np.c_[iris.data.reshape(len(iris.data), -1), iris.target.reshape(len(iris.target), -1)]
np.random.seed(987654321)
np.random.shuffle(Ciris)
shuffledIrisData = Ciris[ :, :iris.data.size//len(iris.data)].reshape(iris.data.shape)
shuffledIrisTarget = Ciris[ :, iris.data.size//len(iris.data) :].reshape(iris.target.shape)
#print (shuffledIrisData)
#print (shuffledIrisTarget)

#Division de l'apprentissage
trainData = shuffledIrisData[:100,:]
trainTarget = shuffledIrisTarget[:100]

#Division du dev
devData = shuffledIrisData[100:130,:]
devTarget = shuffledIrisTarget[100:130]

#Division du test
testData = shuffledIrisData[130:150,:]
testTarget = shuffledIrisTarget[-20:]

p1 = trainData[:,1]
p2 = trainData[:,2]
plt.plot(p1,p2,'*')
plt.show()

/usr/local/lib/python3.5/dist-packages/cairocffi/surfaces.py:651: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  ffi.cast('char*', address), format, width, height, stride)


# <span style="color:green; font-family:Georgia; font-size:1.5em;">2. Phase d'apprentissage </span>

In [3]:
#Mono-Feature

p = [None]*3
m = [None]*3
v = [None]*3

#Calcul de la probabilité à prioris, moyenne et variance d'une seule feature
for i in range(0,3):
    p[i] = (trainTarget == i).sum() / len(trainTarget)
    m[i] = trainData[trainTarget==i][:,0].mean()
    v[i] = trainData[trainTarget==i][:,0].var()
    
print("Proba à prioris : " + str(p))
print("Moyenne Mono-Feature: " + str(m))
print("Variance Mono-Feature: \n" + str(v))

#Calcul de la probabilité à prioris, moyenne et variance de toutes les features
nbFeature = 4
m2 = np.zeros(3*nbFeature).reshape(nbFeature,3)
v2 = np.zeros(3*nbFeature).reshape(nbFeature,3)

for i in range(0,3):
    for j in range(0,nbFeature):
        m2[j,i] = trainData[trainTarget==i][:,j].mean()
        v2[j,i] = trainData[trainTarget==i][:,j].var()
        
print("\nMoyennes multi-feature : \n", m2)
print("\nVariances multi-feature : \n", v2)

Proba à prioris : [0.32000000000000001, 0.37, 0.31]
Moyenne Mono-Feature: [4.9718750000000007, 5.8297297297297295, 6.5451612903225804]
Variance Mono-Feature: 
[0.10264648437500004, 0.23776479181884586, 0.27667013527575451]

Moyennes multi-feature : 
 [[ 4.971875    5.82972973  6.54516129]
 [ 3.390625    2.75405405  3.01612903]
 [ 1.4625      4.16756757  5.51290323]
 [ 0.23125     1.28918919  2.02903226]]

Variances multi-feature : 
 [[ 0.10264648  0.23776479  0.27667014]
 [ 0.11959961  0.09869978  0.08780437]
 [ 0.03734375  0.19786706  0.25080125]
 [ 0.00902344  0.0328561   0.07044745]]


# <span style="color:green; font-family:Georgia; font-size:1.5em;">3. Phase de Developpement </span>

In [4]:
#Fonction calculant la vraissemblance
def calculVrai(x, sigma, mu): 
    res = (1/(sigma*(np.sqrt(2*np.pi))))*np.exp( (-1/2)*((x - mu)/sigma)**2)
    return res

tailleDevTarget = len(devTarget)

#Calcul de la vraissemblance mono-feature
vraissemblance = np.zeros(tailleDevTarget*3).reshape(tailleDevTarget,3)
for i in range (0,tailleDevTarget):
    for j in range(0,3):
        vraissemblance[i,j] = calculVrai(devData[i,j], v[j], m[j])
        
#On cherche le maximum
val = np.argmax(vraissemblance, axis=1)

#On compare les valeurs trouvées et les valeurs de l'énoncé
erreur = 0
for i in range(0,tailleDevTarget):
    if(val[i] != devTarget[i]):
        erreur += 1
        
for i in range(0,tailleDevTarget):
    print("Classe estimee :", val[i], "  Classe target :", devTarget[i])        
        
print("\nTaux d'erreur : " + str(erreur/tailleDevTarget*100),"%")
print("Nb erreurs : ", erreur)

Classe estimee : 2   Classe target : 2.0
Classe estimee : 2   Classe target : 2.0
Classe estimee : 0   Classe target : 0.0
Classe estimee : 0   Classe target : 0.0
Classe estimee : 2   Classe target : 1.0
Classe estimee : 2   Classe target : 1.0
Classe estimee : 0   Classe target : 0.0
Classe estimee : 0   Classe target : 0.0
Classe estimee : 2   Classe target : 1.0
Classe estimee : 2   Classe target : 2.0
Classe estimee : 2   Classe target : 2.0
Classe estimee : 0   Classe target : 0.0
Classe estimee : 2   Classe target : 1.0
Classe estimee : 2   Classe target : 2.0
Classe estimee : 1   Classe target : 0.0
Classe estimee : 0   Classe target : 0.0
Classe estimee : 2   Classe target : 2.0
Classe estimee : 0   Classe target : 0.0
Classe estimee : 2   Classe target : 1.0
Classe estimee : 0   Classe target : 1.0
Classe estimee : 0   Classe target : 0.0
Classe estimee : 2   Classe target : 2.0
Classe estimee : 0   Classe target : 0.0
Classe estimee : 0   Classe target : 0.0
Classe estimee :

In [5]:
#Pour multi-feature, on multiplie les valeurs entre elles et on multiplie par la proba à prioris

proba=(np.ones(tailleDevTarget*3)).reshape(tailleDevTarget,3)

for i in range(0,tailleDevTarget):
    for j in range(0,3):
        for k in range(0,nbFeature):
            proba[i,j] *= calculVrai(devData[i,k], v2[k,j], m2[k,j])
        proba[i,j]*=p[j]

val = np.argmax(proba, axis=1)
erreur = 0
for i in range(0,tailleDevTarget):
    if(val[i] != devTarget[i]):
        erreur += 1

for i in range(0,tailleDevTarget):
    print("Classe estimee : ", val[i], "Classe target : ", devTarget[i])        
        
print("Taux d'erreur : " + str(erreur/tailleDevTarget*100),"%")
print("Nb erreurs : ", erreur)

Classe estimee :  1 Classe target :  2.0
Classe estimee :  2 Classe target :  2.0
Classe estimee :  1 Classe target :  0.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :  1 Classe target :  1.0
Classe estimee :  1 Classe target :  1.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :  2 Classe target :  1.0
Classe estimee :  1 Classe target :  2.0
Classe estimee :  2 Classe target :  2.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :  2 Classe target :  1.0
Classe estimee :  2 Classe target :  2.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :  2 Classe target :  2.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :  1 Classe target :  1.0
Classe estimee :  1 Classe target :  1.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :  2 Classe target :  2.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :

# <span style="color:green; font-family:Georgia; font-size:1.5em;">4. Test des valeurs </span>

In [9]:
proba=(np.ones(20*3)).reshape(20,3)

tailleTestTarget = len(testTarget)

for i in range(0,tailleTestTarget):
    for j in range(0,3):
        for k in range(0,4):
            proba[i,j] *= calculVrai(testData[i,k], v2[k,j], m2[k,j])
        proba[i,j]*=p[j]
        
val = np.argmax(proba, axis=1)
erreur = 0
for i in range(0,tailleTestTarget):
    if(val[i] != testTarget[i]):
        erreur += 1
for i in range(0,tailleTestTarget):
    print("Classe estimee : ", val[i], "Classe target : ", testTarget[i])        
        
print("Taux d'erreur : " + str(erreur/30*100), "%")
print("Nb erreurs : ", erreur)


Classe estimee :  2 Classe target :  2.0
Classe estimee :  2 Classe target :  2.0
Classe estimee :  2 Classe target :  1.0
Classe estimee :  2 Classe target :  2.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :  2 Classe target :  2.0
Classe estimee :  1 Classe target :  1.0
Classe estimee :  2 Classe target :  2.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :  2 Classe target :  1.0
Classe estimee :  1 Classe target :  1.0
Classe estimee :  2 Classe target :  2.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :  1 Classe target :  1.0
Classe estimee :  0 Classe target :  0.0
Classe estimee :  1 Classe target :  1.0
Classe estimee :  2 Classe target :  2.0
Classe estimee :  2 Classe target :  2.0
Classe estimee :  0 Classe target :  0.0
Taux d'erreur : 6.666666666666667 %
Nb erreurs :  2
